type User{
    _id: ID
    username: String! @unique
    email: String! @unique
    password: String!
    avatar: String
    joinDate: String
    bookmarks: [Article]
}
type Article{
    _id: ID
    title: String!
    imageUrl: String
    kind: [String]
    description: String!
    createDate: String
    trumbs_up: Int
    createdBy: User!
    messages: [Message]
}
type Token {
    token: String!
}
type Message {
    _id: ID
    messsageDetail: String!
    messageUser: User!
}
type Mutation {
    signinUser(username:String!, password: String!): Token!
    signupUser(username:String!, email: String!,password: String!): Token!
    createArticle(title: String!, imageUrl: String,kind: [String]!, description:String!,trumbs_up:Int,createdBy:ID!): Article!
}
type Query{
    currentUser: User
    getUser: [User]
    getArticle: [Article]
}